#!/bin/bash
subdomain=$1
origin='$ORIGIN'
ttl='$TTL 300'
h1='"'
main='jordy-deboeck.sasm.uclllabs.be'
serial=$(cat /etc/bind/db.jordy-deboeck.sasm.uclllabs.be | grep -P 'Serial' | grep -P [0-9] | grep -oP '\b(?<!\.)\d+(?!\.)\b');
newSerial=$(($serial + 1))


echo "zone $h1$subdomain.$main$h1 {
type master;
file $h1/etc/bind/ScriptZones/db.$subdomain.jordy-deboeck.sasm.uclllabs.be$h1;
};
" >> /etc/bind/named.conf.mrt-zones

echo "$ttl
$origin $subdomain.jordy-deboeck.sasm.uclllabs.be.
@       IN      SOA     $subdomain.jordy-deboeck.sasm.uclllabs.be. root.jordy-deboeck.sasm.uclllabs.be. (
                              1         ; Serial
                            300         ; Refresh
                            300         ; Retry
                            300         ; Expire
                          300 ) ; Negative Cache TTL
;name servers
        IN      NS      ns.jordy-deboeck.sasm.uclllabs.be.
ns      IN      A       193.191.177.221
" > /etc/bind/ScriptZones/db.$subdomain.jordy-deboeck.sasm.uclllabs.be


echo "$subdomain        IN      NS      ns.jordy-deboeck.sasm.uclllabs.be." >> /etc/bind/db.jordy-deboeck.sasm.uclllabs.be
sed -i "s/$serial\t\t;\sSerial/$newSerial\t\t; Serial/" /etc/bind/db.jordy-deboeck.sasm.uclllabs.be




sudo systemctl restart named.service;
