#!/bin/bash
subdomain=$1
ttl="\$TTL 300"
maindomain="jordy-deboeck.sasm.uclllabs.be"
conf="/etc/bind/named.conf.mrt-zones"
zonedomain="/etc/bind/ScriptZones/db.$subdomain.$maindomain"

echo "zone \"$subdomain.$maindomain\" { type master; file \"$zonedomain\"; };" >> "$conf"

echo "$ttl
@	IN	SOA	$subdomain.$maindomain. root.localhost. (
				  1	; Serial
				300	; Refresh
				300	; Retry
				300	; Expire
				300 )	; Negative Cache TTL
; name servers
@	IN	NS	ns.$maindomain.
ns	IN	A	193.191.176.39
" >> "$zonedomain"

serial=$(grep -P 'Serial' "/etc/bind/Zones/db.jordy-deboeck.sasm.uclllabs.be" | grep -P [0-9] | grep -oP '\b(?<!\.)\d+(?!\.)\b')
newSerial=$((serial + 1))

echo $newSerial

echo "$subdomain.$maindomain. IN NS ns.$maindomain." >> "/etc/bind/Zones/db.$maindomain"
sed -i "s/$serial/$newSerial/" "/etc/bind/Zones/db.$maindomain"

systemctl restart named
