#!/bin/bash
while getopts ":t:" opt; do
	case $opt in
		t)
			if [ -n "$OPTARG" ]; then
				record_type="$OPTARG"
				shift 2
			else
				echo "Option -t requires an argument." >&2
				exit 1
			fi
		;;
	esac
done

case $record_type in
	A)
		echo "$1 in A $2" >> "/etc/bind/ScriptZones/db.$3"
	;;
	MX)
		echo "@ IN MX $1.$3" >> "/etc/bind/ScriptZones/db.$3"
		echo "$1.$3 IN A $2" >> "/etc/bind/ScriptZones/db.$3"
	;;
	CNAME) 
		echo "$1 IN CNAME $2" >> "$3"
	;;
	*) echo "Invalid record type: $record_type."
esac

systemctl restart named
