#!/bin/bash

if [ "$EUID" -ne 0 ]; then
  echo "EE not executed as root"
  exit
fi

if [ -z "$1" ]; then
  echo "EE no zone provided"
  exit 1
fi

zone="$1"
zone_ip=$(dig +short +nocmd +nocomments +noquestion +noauthority +noadditional $zone @8.8.8.8)

if ! [ -n "$zone_ip" ]; then
  echo "EE $zone does not exist"
  exit 1
fi

site_conf_root="/etc/apache2/sites-available/"
site="999-${zone}"
site_conf="$site_conf_root/$site.conf"

document_root="/var/www/html/$zone"

if ! [ -d "$document_root" ]; then
  mkdir "$document_root"
fi

cat > "$site_conf" <<EOL
<VirtualHost *:80>
  ServerAdmin root@jordy-deboeck.sasm.uclllabs.be
  ServerName $zone
  DocumentRoot $document_root
  ErrorLog \${APACHE_LOG_DIR}/$zone.error.log
  CustomLog \${APACHE_LOG_DIR}/$zone.access.log combined
</VirtualHost>
EOL

echo "welcome $zone" > "$document_root/index.html"

a2ensite $site
systemctl reload apache2.service
